MODULES=(i2c_bcm2835 i2c_mux i2c_mux_pinctrl waveshare_panel_regulator panel_waveshare_dsi_v2 goodix_ts vc4)
HOOKS=(base systemd plymouth autodetect microcode modconf kms keyboard sd-vconsole block filesystems fsck)

