[core]
plugins = \
  autostart \
  expo \
  scale \
  move \
  resize \
  vswitch \
  window-rules \
  place \
  grid \
  command \
  wm-actions

close_top_view = swipe down 2
vwidth = 2
vheight = 1

[autostart]
background = swaybg -i /home/alarm/background_saab.png -m fill
desktop = pcmanfm-qt --desktop
panel = waybar
# keyboard = wvkbd-mobintl --hidden -L 320 --fn "JetBrainsMono Nerd Font 16"
polkit = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

[output:DSI-1]
mode = 800x1280@60
transform = 90
scale = 1.0

[input]
click_method = clickfinger
natural_scroll = true
xkb_layout = se

[input-device:10-005d Goodix Capacitive TouchScreen]
output = DSI-1

[touch]
swipe_fingers = 2

[vswitch]
binding_left = swipe right 2
binding_right = swipe left 2

[expo]
toggle = swipe up 3
duration = 300

[scale]
toggle = <super> KEY_A
duration = 300

[command]
binding_close = swipe down 2
