interface=wlan0
driver=nl80211
ssid=SAAB 95

country_code=SE
ieee80211d=1
ieee80211h=0

hw_mode=a
channel=36

ieee80211n=1
ieee80211ac=1
wmm_enabled=1
ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40]
vht_oper_chwidth=1
vht_oper_centr_freq_seg0_idx=42

wpa=2
wpa_passphrase=saab9595baas
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
auth_algs=1

ctrl_interface=/run/hostapd
ctrl_interface_group=wheel
