font_family      JetBrainsMono Nerd Font
font_size        14.0

# touch-friendly
window_padding_width 8
tab_bar_edge top
tab_bar_style powerline

# scrollback
scrollback_lines 10000

# close without confirmation
confirm_os_window_close 0

background_opacity 0.90

startup_session ~/.config/kitty/sessions/max.conf
